version: '3'

services:
  tchos_cms_prod:
    container_name: tchos_cms_prod
    image: 188547014787.dkr.ecr.us-east-1.amazonaws.com/thechosen-wordpress:prod-latest
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
      WORDPRESS_DB_NAME: $DB_NAME
      WORDPRESS_DB_HOST: $DB_HOST:$DB_PORT
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DB_USER: $DB_USER
      WORDPRESS_DB_PASSWORD: $DB_PASSWORD
      WORDPRESS_SITE_URL: $SITE_URL
      WORDPRESS_DEBUG: $DEBUG
    expose:
      - 80:80
    ports:
      - 80:80
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8GB
        reservations:
          cpus: '2'
          memory: 4GB
      x-aws-min_percent: 30
      x-aws-autoscaling:
        desired: 1
        min: 1
        max: 3 # Required
        cpu: 50
    restart: always
volumes:
  dbdata: