<?php
/*
 * FOR POST TYPES:
 * Add this 3 arguments inside array props on register_post_type() function .ex:
 *
 * register_post_type( 'translation', array(
 * 	...
 * 	'show_in_graphql' => true,
 * 	'graphql_single_name' => 'Translation',
 * 	'graphql_plural_name' => 'Translations'
 * ) );
 *
*/

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
		'key' => 'group_64809b459da9e',
		'title' => 'Translation fields',
		'fields' => array(
			array(
				'key' => 'field_64809b97b9ee7',
				'label' => 'Translation rows',
				'name' => 'translation_rows',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'show_in_graphql' => 1,
				'acfe_repeater_stylised_button' => 0,
				'layout' => 'table',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Add Row',
				'rows_per_page' => 20,
				'wpml_cf_preferences' => 1,
				'sub_fields' => array(
					array(
						'key' => 'field_6480ac4d440f4',
						'label' => 'Key',
						'name' => 'key',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'show_in_graphql' => 1,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_64809b97b9ee7',
						'wpml_cf_preferences' => 2,
					),
					array(
						'key' => 'field_6480ac59440f5',
						'label' => 'Value',
						'name' => 'value',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'show_in_graphql' => 1,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_64809b97b9ee7',
						'wpml_cf_preferences' => 2,
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'translation',
				),
				array(
					'param' => 'post',
					'operator' => '!=',
					'value' => '269',
				),
				array(
					'param' => 'post',
					'operator' => '!=',
					'value' => '8',
				),
				array(
					'param' => 'post',
					'operator' => '!=',
					'value' => '2033',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'acfe_display_title' => '',
		'acfe_autosync' => array(
			0 => 'php',
		),
		'acfml_field_group_mode' => 'translation',
		'acfe_form' => 0,
		'acfe_meta' => '',
		'acfe_note' => '',
		'show_in_graphql' => 1,
		'graphql_field_name' => 'translationFields',
		'map_graphql_types_from_location_rules' => 1,
		'graphql_types' => array(
			0 => 'Translation',
		),
	) );
} );




add_action( 'init', function() {
	register_post_type( 'translation', array(
		'labels' => array(
			'name' => 'Translations',
			'singular_name' => 'Translation',
			'menu_name' => 'Translations',
			'all_items' => 'All Translations',
			'edit_item' => 'Edit Translation',
			'view_item' => 'View Translation',
			'view_items' => 'View Translations',
			'add_new_item' => 'Add New Translation',
			'new_item' => 'New Translation',
			'parent_item_colon' => 'Parent Translation:',
			'search_items' => 'Search Translations',
			'not_found' => 'No translations found',
			'not_found_in_trash' => 'No translations found in Trash',
			'archives' => 'Translation Archives',
			'attributes' => 'Translation Attributes',
			'insert_into_item' => 'Insert into translation',
			'uploaded_to_this_item' => 'Uploaded to this translation',
			'filter_items_list' => 'Filter translations list',
			'filter_by_date' => 'Filter translations by date',
			'items_list_navigation' => 'Translations list navigation',
			'items_list' => 'Translations list',
			'item_published' => 'Translation published.',
			'item_published_privately' => 'Translation published privately.',
			'item_reverted_to_draft' => 'Translation reverted to draft.',
			'item_scheduled' => 'Translation scheduled.',
			'item_updated' => 'Translation updated.',
			'item_link' => 'Translation Link',
			'item_link_description' => 'A link to a translation.',
		),
		'public' => true,
		'show_in_rest' => true,
		'menu_icon' => 'dashicons-admin-site',
		'supports' => array(
			0 => 'title',
		),
		'delete_with_user' => false,
		//
		'show_in_graphql' => true,
		'graphql_single_name' => 'Translation',
		'graphql_plural_name' => 'Translations'
	) );

  register_post_type( 'vanity-url', array(
		'labels' => array(
			'name' => 'Vanity URLs',
			'singular_name' => 'Vanity URL',
			'menu_name' => 'Vanity URLs',
			'all_items' => 'All Vanity URLs',
			'edit_item' => 'Edit Vanity URL',
			'view_item' => 'View Vanity URL',
			'view_items' => 'View Vanity URLs',
			'add_new_item' => 'Add New Vanity URL',
			'new_item' => 'New Vanity URL',
			'parent_item_colon' => 'Parent Vanity URL:',
			'search_items' => 'Search Vanity URLs',
			'not_found' => 'No vanity urls found',
			'not_found_in_trash' => 'No vanity urls found in Trash',
			'archives' => 'Vanity URL Archives',
			'attributes' => 'Vanity URL Attributes',
			'insert_into_item' => 'Insert into vanity url',
			'uploaded_to_this_item' => 'Uploaded to this vanity url',
			'filter_items_list' => 'Filter vanity urls list',
			'filter_by_date' => 'Filter vanity urls by date',
			'items_list_navigation' => 'Vanity URLs list navigation',
			'items_list' => 'Vanity URLs list',
			'item_published' => 'Vanity URL published.',
			'item_published_privately' => 'Vanity URL published privately.',
			'item_reverted_to_draft' => 'Vanity URL reverted to draft.',
			'item_scheduled' => 'Vanity URL scheduled.',
			'item_updated' => 'Vanity URL updated.',
			'item_link' => 'Vanity URL Link',
			'item_link_description' => 'A link to a vanity url.',
		),
		'public' => true,
		'show_in_rest' => true,
		'menu_icon' => 'dashicons-admin-links',
		'supports' => array(
			0 => 'title',
		),
		'delete_with_user' => false,
    //
		'show_in_graphql' => true,
		'graphql_single_name' => 'VanityURL',
		'graphql_plural_name' => 'VanityURLs'
	) );

	register_post_type( 'cast-member', array(
		'labels' => array(
			'name' => 'Cast members',
			'singular_name' => 'Cast member',
			'menu_name' => 'Cast members',
			'all_items' => 'All Cast members',
			'edit_item' => 'Edit Cast member',
			'view_item' => 'View Cast member',
			'view_items' => 'View Cast members',
			'add_new_item' => 'Add New Cast member',
			'new_item' => 'New Cast member',
			'parent_item_colon' => 'Parent Cast member:',
			'search_items' => 'Search Cast members',
			'not_found' => 'No cast members found',
			'not_found_in_trash' => 'No cast members found in Trash',
			'archives' => 'Cast member Archives',
			'attributes' => 'Cast member Attributes',
			'insert_into_item' => 'Insert into cast member',
			'uploaded_to_this_item' => 'Uploaded to this cast member',
			'filter_items_list' => 'Filter cast members list',
			'filter_by_date' => 'Filter cast members by date',
			'items_list_navigation' => 'Cast members list navigation',
			'items_list' => 'Cast members list',
			'item_published' => 'Cast member published.',
			'item_published_privately' => 'Cast member published privately.',
			'item_reverted_to_draft' => 'Cast member reverted to draft.',
			'item_scheduled' => 'Cast member scheduled.',
			'item_updated' => 'Cast member updated.',
			'item_link' => 'Cast member Link',
			'item_link_description' => 'A link to a cast member.',
		),
		'public' => true,
		'show_in_rest' => true,
		'menu_icon' => 'dashicons-megaphone',
		'supports' => array(
			0 => 'title',
		),
		'taxonomies' => array(
			0 => 'category',
			1 => 'post_tag',
		),
		'delete_with_user' => false,
		'show_in_graphql' => true,
		'graphql_single_name' => 'CastMember',
		'graphql_plural_name' => 'CastMembers'
	) );
	register_post_type( 'cast-member', array(
		'labels' => array(
			'name' => 'Cast members',
			'singular_name' => 'Cast member',
			'menu_name' => 'Cast members',
			'all_items' => 'All Cast members',
			'edit_item' => 'Edit Cast member',
			'view_item' => 'View Cast member',
			'view_items' => 'View Cast members',
			'add_new_item' => 'Add New Cast member',
			'new_item' => 'New Cast member',
			'parent_item_colon' => 'Parent Cast member:',
			'search_items' => 'Search Cast members',
			'not_found' => 'No cast members found',
			'not_found_in_trash' => 'No cast members found in Trash',
			'archives' => 'Cast member Archives',
			'attributes' => 'Cast member Attributes',
			'insert_into_item' => 'Insert into cast member',
			'uploaded_to_this_item' => 'Uploaded to this cast member',
			'filter_items_list' => 'Filter cast members list',
			'filter_by_date' => 'Filter cast members by date',
			'items_list_navigation' => 'Cast members list navigation',
			'items_list' => 'Cast members list',
			'item_published' => 'Cast member published.',
			'item_published_privately' => 'Cast member published privately.',
			'item_reverted_to_draft' => 'Cast member reverted to draft.',
			'item_scheduled' => 'Cast member scheduled.',
			'item_updated' => 'Cast member updated.',
			'item_link' => 'Cast member Link',
			'item_link_description' => 'A link to a cast member.',
		),
		'public' => true,
		'show_in_rest' => true,
		'menu_icon' => 'dashicons-megaphone',
		'supports' => array(
			0 => 'title',
		),
		'taxonomies' => array(
			0 => 'category',
			1 => 'post_tag',
		),
		'delete_with_user' => false,
		'show_in_graphql' => true,
		'graphql_single_name' => 'CastMember',
		'graphql_plural_name' => 'CastMembers'
	) );

	register_post_type( 'chosencon-event', array(
		'labels' => array(
			'name' => 'ChosenCon Events',
			'singular_name' => 'ChosenCon Event',
			'menu_name' => 'ChosenCon Events',
			'all_items' => 'All Events',
			'edit_item' => 'Edit Event',
			'view_item' => 'View Event',
			'view_items' => 'View Events',
			'add_new_item' => 'Add New Event',
			'new_item' => 'New Event',
			'parent_item_colon' => 'Parent Event:',
			'search_items' => 'Search ChosenCon Event',
			'not_found' => 'No Event found',
			'not_found_in_trash' => 'No Event found in Trash',
			'archives' => 'ChosenCon Event Archives',
			'attributes' => 'ChosenCon Event Attributes',
			'insert_into_item' => 'Insert into event',
			'uploaded_to_this_item' => 'Uploaded to this event',
			'filter_items_list' => 'Filter event list',
			'filter_by_date' => 'Filter event by date',
			'items_list_navigation' => 'Events list navigation',
			'items_list' => 'Event list',
			'item_published' => 'Event published.',
			'item_published_privately' => 'Event published privately.',
			'item_reverted_to_draft' => 'Event reverted to draft.',
			'item_scheduled' => 'Event scheduled.',
			'item_updated' => 'Event updated.',
			'item_link' => 'Event Link',
			'item_link_description' => 'A link to a event.',
		),
		'public' => true,
		'show_in_rest' => true,
		'menu_icon' => 'dashicons-calendar',
		'supports' => array(
			0 => 'title',
			1 => 'editor',
			2 => 'excerpt',
		),
		'taxonomies' => array(
			0 => 'schedule-day',
			1 => 'schedule-hour',
			2 => 'schedule-location',
			3 => 'schedule-modalities',
		),
		'delete_with_user' => false,
		'show_in_graphql' => true,
		'graphql_single_name' => 'ChosenConEvent',
		'graphql_plural_name' => 'ChosenConEvents'
	) );

	register_taxonomy( 'schedule-day', array(
		0 => 'chosencon-event',
	), array(
		'labels' => array(
			'name' => 'Days',
			'singular_name' => 'Day',
			'menu_name' => 'Days',
			'all_items' => 'All Days',
			'edit_item' => 'Edit Day',
			'view_item' => 'View Day',
			'update_item' => 'Update Day',
			'add_new_item' => 'Add New Day',
			'new_item_name' => 'New Day Name',
			'search_items' => 'Search Days',
			'popular_items' => 'Popular Days',
			'separate_items_with_commas' => 'Separate days with commas',
			'add_or_remove_items' => 'Add or remove days',
			'choose_from_most_used' => 'Choose from the most used days',
			'not_found' => 'No days found',
			'no_terms' => 'No days',
			'items_list_navigation' => 'Days list navigation',
			'items_list' => 'Days list',
			'back_to_items' => '← Go to days',
			'item_link' => 'Day Link',
			'item_link_description' => 'A link to a day',
		),
		'public' => true,
		'show_in_menu' => true,
		'show_in_rest' => true,
		'show_in_graphql' => true,
		'graphql_single_name' => 'ScheduleDay',
		'graphql_plural_name' => 'ScheduleDays'
	) );

	register_taxonomy( 'schedule-hour', array(
		0 => 'chosencon-event',
	), array(
		'labels' => array(
			'name' => 'Hours',
			'singular_name' => 'Hour',
			'menu_name' => 'Hours',
			'all_items' => 'All Hours',
			'edit_item' => 'Edit Hour',
			'view_item' => 'View Hour',
			'update_item' => 'Update Hour',
			'add_new_item' => 'Add New Hour',
			'new_item_name' => 'New Hour Name',
			'search_items' => 'Search Hours',
			'popular_items' => 'Popular Hours',
			'separate_items_with_commas' => 'Separate hours with commas',
			'add_or_remove_items' => 'Add or remove hours',
			'choose_from_most_used' => 'Choose from the most used hours',
			'not_found' => 'No hours found',
			'no_terms' => 'No hours',
			'items_list_navigation' => 'Hours list navigation',
			'items_list' => 'Hours list',
			'back_to_items' => '← Go to hours',
			'item_link' => 'Hour Link',
			'item_link_description' => 'A link to a hour',
		),
		'public' => true,
		'show_in_menu' => true,
		'show_in_rest' => true,
		'show_in_graphql' => true,
		'graphql_single_name' => 'ScheduleHour',
		'graphql_plural_name' => 'ScheduleHours'
	) );

	register_taxonomy( 'schedule-location', array(
		0 => 'chosencon-event',
	), array(
		'labels' => array(
			'name' => 'Locations',
			'singular_name' => 'Location',
			'menu_name' => 'Locations',
			'all_items' => 'All Locations',
			'edit_item' => 'Edit Location',
			'view_item' => 'View Location',
			'update_item' => 'Update Location',
			'add_new_item' => 'Add New Location',
			'new_item_name' => 'New Location Name',
			'search_items' => 'Search Locations',
			'popular_items' => 'Popular Locations',
			'separate_items_with_commas' => 'Separate locations with commas',
			'add_or_remove_items' => 'Add or remove locations',
			'choose_from_most_used' => 'Choose from the most used locations',
			'not_found' => 'No locations found',
			'no_terms' => 'No locations',
			'items_list_navigation' => 'Locations list navigation',
			'items_list' => 'Locations list',
			'back_to_items' => '← Go to locations',
			'item_link' => 'Location Link',
			'item_link_description' => 'A link to a location',
		),
		'public' => true,
		'show_in_menu' => true,
		'show_in_rest' => true,
		'show_in_graphql' => true,
		'graphql_single_name' => 'ScheduleLocation',
		'graphql_plural_name' => 'ScheduleLocations'
	) );

	register_taxonomy( 'schedule-modalities', array(
		0 => 'chosencon-event',
	), array(
		'labels' => array(
			'name' => 'Modality',
			'singular_name' => 'Modalities',
			'menu_name' => 'Modality',
			'all_items' => 'All Modality',
			'edit_item' => 'Edit Modalities',
			'view_item' => 'View Modalities',
			'update_item' => 'Update Modalities',
			'add_new_item' => 'Add New Modalities',
			'new_item_name' => 'New Modalities Name',
			'search_items' => 'Search Modality',
			'popular_items' => 'Popular Modality',
			'separate_items_with_commas' => 'Separate modality with commas',
			'add_or_remove_items' => 'Add or remove modality',
			'choose_from_most_used' => 'Choose from the most used modality',
			'not_found' => 'No modality found',
			'no_terms' => 'No modality',
			'items_list_navigation' => 'Modality list navigation',
			'items_list' => 'Modality list',
			'back_to_items' => '← Go to modality',
			'item_link' => 'Modalities Link',
			'item_link_description' => 'A link to a modalities',
		),
		'public' => true,
		'show_in_menu' => true,
		'show_in_rest' => true,
		'show_in_graphql' => true,
		'graphql_single_name' => 'ScheduleModality',
		'graphql_plural_name' => 'ScheduleModalities'
	) );
} );